# Generated by Django 4.1.7 on 2023-03-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile_biography_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.userprofile'),
            preserve_default=False,
        ),
    ]
