# Generated by Django 4.1.7 on 2023-03-07 21:23

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
