# Generated by Django 4.1.7 on 2023-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comments_approved_alter_comments_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='development',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
