# Generated by Django 4.1.7 on 2023-03-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_category_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_profile',
            new_name='user',
        ),
    ]
