# Generated by Django 4.1.7 on 2023-03-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_user_profile_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created'], 'verbose_name': 'Blog Comments', 'verbose_name_plural': 'Blog Comments'},
        ),
    ]
