# Generated by Django 4.1.7 on 2023-03-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='approved',
        ),
    ]
